# Generated by Django 5.1.4 on 2025-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlumniApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_Name", models.CharField(max_length=500)),
                ("blog_Details", models.CharField(max_length=1000)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_posts"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="usersData/"),
                ),
                ("user_Email", models.EmailField(max_length=200, unique=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("ALUMNI", "Alumni"),
                            ("STUDENT", "Student"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Computer Science and Engineering",
                                "Computer Science and Engineering",
                            ),
                            ("Electrical Engineering", "Electrical Engineering"),
                            ("Electronics Engineering", "Electronics Engineering"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enrollment_Number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1st Year", "1st Year"),
                            ("2nd Year", "2nd Year"),
                            ("3rd Year", "3rd Year"),
                            ("Passout", "Passout"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("user_Password", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
